name: Realese # name of the action (displayed in the github interface)

on: # event list
  push:
    branches:
      - main

env: # environment variables (available in any part of the action)
  NODE_VERSION: 18

jobs: # list of things to do
  build:
    name: Build # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    permissions:
      contents: write
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: extension-${{ steps.package-version.outputs.current-version }}
          path: dist/
          retention-days: 1

      - name: Zip Folder
        run: zip -r extension-${{ steps.package-version.outputs.current-version }}.zip dist/

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
          artifacts: extension-${{ steps.package-version.outputs.current-version }}.zip
          generateReleaseNotes: true
          removeArtifacts: true
          skipIfReleaseExists: true
